changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      commit_patterns:
        - '^(?<type>\w+(?:\((?<scope>[^)]+)\))?!:\s*)'
        - '^Breaking\b'
      semver: major
    - title: Features
      labels:
        - enhancement
        - feature
      commit_patterns:
        - '^(?<type>feat(?:\((?<scope>[^)]+)\))?!?:\s*)'
        - '^(Add|Create|Enable|Implement|Introduce|Publish|Separate|Support)\b'
      semver: minor
    - title: Fixes
      labels:
        - bug
        - security
      commit_patterns:
        - '^(?<type>(?:fix|security)(?:\((?<scope>[^)]+)\))?!?:\s*)'
        - '^Revert "'
        - '^(Avoid|Bound|Correct|Fix|Handle|Keep|Match|Prevent|Protect|Reject|Restore)\b'
      semver: patch
    - title: Internal Changes
      commit_patterns:
        - '^(?<type>(?:build|chore|ci|docs?|meta|perf|refactor|style|tests?)(?:\((?<scope>[^)]+)\))?!?:\s*)'
      semver: patch
    - title: Other Changes
      labels:
        - '*'
      semver: patch
